// main.go は internal/codegen を実行可能にするエントリポイントです。
//
// `go run ./internal/codegen` を実行すると、リポジトリルートの api/swagger.json
// を読み込み、internal/misoca/models_gen.go を再生成します。
package main

import (
	"flag"
	"fmt"
	"os"
)

func main() {
	inPath := flag.String("in", "api/swagger.json", "入力とするSwagger仕様書のパス")
	outPath := flag.String("out", "internal/misoca/models_gen.go", "生成したGoソースの出力先パス")
	flag.Parse()

	if err := run(*inPath, *outPath); err != nil {
		fmt.Fprintf(os.Stderr, "misoca-cli codegen: %v\n", err)
		os.Exit(1)
	}
}

func run(inPath, outPath string) error {
	raw, err := os.ReadFile(inPath)
	if err != nil {
		return fmt.Errorf("入力ファイルの読み込みに失敗しました: %w", err)
	}

	generated, err := GenerateModels(raw)
	if err != nil {
		return fmt.Errorf("モデルの生成に失敗しました: %w", err)
	}

	header := []byte("// Code generated by internal/codegen from api/swagger.json. DO NOT EDIT.\n\n")
	if err := os.WriteFile(outPath, append(header, generated...), 0o644); err != nil {
		return fmt.Errorf("出力ファイルの書き込みに失敗しました: %w", err)
	}
	return nil
}
