// Code generated by internal/codegen from api/swagger.json. DO NOT EDIT.

package misoca

// Contact は ApiEntity_Contact model を表す構造体です。
type Contact struct {
	// 取引先を識別する一意なID
	ContactGroupID *int `json:"contact_group_id,omitempty"`
	// 法人番号
	CorporateNumber *string `json:"corporate_number,omitempty"`
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// お気に入りかどうか（お気に入りの場合true）
	Favorited *bool `json:"favorited,omitempty"`
	// お気に入りにした日時
	FavoritedAt *string `json:"favorited_at,omitempty"`
	// 送り先を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// 覚え書きメモ欄
	Memo *string `json:"memo,omitempty"`
	// 送付先住所1
	RecipientAddress1 *string `json:"recipient_address1,omitempty"`
	// 送付先住所2
	RecipientAddress2 *string `json:"recipient_address2,omitempty"`
	// 管理コード
	RecipientCode *string `json:"recipient_code,omitempty"`
	// FAX番号
	RecipientFaxNo *string `json:"recipient_fax_no,omitempty"`
	// メールアドレス
	RecipientMailAddress *string `json:"recipient_mail_address,omitempty"`
	// メールアドレス(CC)
	RecipientMailAddressCc *string `json:"recipient_mail_address_cc,omitempty"`
	// 名前
	RecipientName *string `json:"recipient_name,omitempty"`
	// 送付先名称1
	RecipientName1 *string `json:"recipient_name1,omitempty"`
	// 送付先名称2
	RecipientName2 *string `json:"recipient_name2,omitempty"`
	// 送付先名称3
	RecipientName3 *string `json:"recipient_name3,omitempty"`
	// 送付先名称4
	RecipientName4 *string `json:"recipient_name4,omitempty"`
	// 担当者
	RecipientNotes *string `json:"recipient_notes,omitempty"`
	// ふりがな
	RecipientRuby *string `json:"recipient_ruby,omitempty"`
	// 電話番号
	RecipientTelNo *string `json:"recipient_tel_no,omitempty"`
	// 敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 送付先敬称
	RecipientTitle2 *string `json:"recipient_title2,omitempty"`
	// 送付先郵便番号
	RecipientZipCode *string `json:"recipient_zip_code,omitempty"`
	// 消費税設定('USE_SENDER': 自社情報の設定, 'INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税), 'NONENTRY': 税別表示(納品書のみ請求時に計算))
	TaxOption *string `json:"tax_option,omitempty"`
	// 非表示にされたかどうか(非表示にされている場合true)
	Trashed *bool `json:"trashed,omitempty"`
	// 非表示にされた日時
	TrashedAt *string `json:"trashed_at,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ユーザID
	UserID *int `json:"user_id,omitempty"`
}

// ContactGroup は ApiEntity_ContactGroup model を表す構造体です。
type ContactGroup struct {
	BankAccounts []InvoiceBankAccount `json:"bank_accounts,omitempty"`
	// 法人番号
	CorporateNumber *string `json:"corporate_number,omitempty"`
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// 取引先を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// メールの件名
	MailSettings *ContactGroupMailSettings `json:"mail_settings,omitempty"`
	// Peppol ID
	PeppolID *string `json:"peppol_id,omitempty"`
	// 名前
	RecipientName *string `json:"recipient_name,omitempty"`
	// ふりがな
	RecipientRuby *string `json:"recipient_ruby,omitempty"`
	// 敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 消費税設定('USE_SENDER': 自社情報の設定, 'INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税), 'NONENTRY': 税別表示(納品書のみ請求時に計算))
	TaxOption *string `json:"tax_option,omitempty"`
	// 非表示にされたかどうか(非表示にされている場合true)
	Trashed *bool `json:"trashed,omitempty"`
	// 非表示にされた日時
	TrashedAt *string `json:"trashed_at,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ユーザID
	UserID *int `json:"user_id,omitempty"`
}

// ContactGroupMailSettings は  を表す構造体です。
type ContactGroupMailSettings struct {
	Subjects *ContactGroupMailSettingsSubjects `json:"subjects,omitempty"`
}

// ContactGroupMailSettingsSubjects は  を表す構造体です。
type ContactGroupMailSettingsSubjects struct {
	// 納品書
	DeliverySlip *string `json:"delivery_slip,omitempty"`
	// 見積書
	Estimate *string `json:"estimate,omitempty"`
	// 請求書
	Invoice *string `json:"invoice,omitempty"`
	// 領収書
	SimplifiedInvoice *string `json:"simplified_invoice,omitempty"`
}

// DealingItem は ApiEntity_DealingItem model を表す構造体です。
type DealingItem struct {
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// 源泉徴収税フラグ
	ExcludingWithholdingTax *bool `json:"excluding_withholding_tax,omitempty"`
	// 品目を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// 品番・品名
	Name *string `json:"name,omitempty"`
	// 消費税区分('USE_SENDER': 自社情報の設定, 'STANDARD_TAX_10': 10%, 'REDUCED_TAX_8': 軽減8%, 'STANDARD_TAX_8': 8%, 'STANDARD_TAX_5': 5%, 'EXEMPTED_TAX': 対象外)
	TaxType *string `json:"tax_type,omitempty"`
	// 単位
	UnitName *string `json:"unit_name,omitempty"`
	// 単価
	UnitPrice *Number `json:"unit_price,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// DeliverySlip は ApiEntity_DeliverySlip model を表す構造体です。
type DeliverySlip struct {
	// 処理済みに移動した日時
	ArchivedAt *string                   `json:"archived_at,omitempty"`
	Body       *DeliverySlipDocumentBody `json:"body,omitempty"`
	// 送り先を識別する一意なID。取引先を削除した場合もIDは残ります
	ContactID *int `json:"contact_id,omitempty"`
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// 納品日
	DeliveryDate *string `json:"delivery_date,omitempty"`
	// 納品書番号
	DeliverySlipNumber *string `json:"delivery_slip_number,omitempty"`
	// 発行ステータス
	DeliverySlipStatus *int `json:"delivery_slip_status,omitempty"`
	// 納品書を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 発行日
	IssueDate *string `json:"issue_date,omitempty"`
	// 発行済かどうか（発行済の場合true）
	Issued *bool                      `json:"issued,omitempty"`
	Items  []DeliverySlipDocumentItem `json:"items,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// 納品ステータス
	PaymentStatus *int `json:"payment_status,omitempty"`
	// 取引先名
	RecipientName *string `json:"recipient_name,omitempty"`
	// 担当者
	RecipientNotes *string `json:"recipient_notes,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 件名
	Subject *string `json:"subject,omitempty"`
	// ごみ箱に移動した日時
	TrashedAt *string `json:"trashed_at,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ユーザID
	UserID *int `json:"user_id,omitempty"`
}

// DeliverySlipDocumentBody は  を表す構造体です。
type DeliverySlipDocumentBody struct {
	// 備考
	Notes *string `json:"notes,omitempty"`
	// 社内メモ
	PrivateSenderMemo *string `json:"private_sender_memo,omitempty"`
	// 取引先住所1
	RecipientAddress1 *string `json:"recipient_address1,omitempty"`
	// 取引先住所2
	RecipientAddress2 *string `json:"recipient_address2,omitempty"`
	// 取引先名1
	RecipientName1 *string `json:"recipient_name1,omitempty"`
	// 取引先名2
	RecipientName2 *string `json:"recipient_name2,omitempty"`
	// 取引先名3
	RecipientName3 *string `json:"recipient_name3,omitempty"`
	// 取引先名4
	RecipientName4 *string `json:"recipient_name4,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 取引先郵便番号
	RecipientZipCode *string `json:"recipient_zip_code,omitempty"`
	// 自社住所1
	SenderAddress1 *string `json:"sender_address1,omitempty"`
	// 自社住所2
	SenderAddress2 *string `json:"sender_address2,omitempty"`
	// 自社住所3
	SenderAddress3 *string `json:"sender_address3,omitempty"`
	// 自社Email
	SenderEmail *string `json:"sender_email,omitempty"`
	// 自社FAX
	SenderFax *string `json:"sender_fax,omitempty"`
	// 自社名1
	SenderName1 *string `json:"sender_name1,omitempty"`
	// 自社名2
	SenderName2 *string `json:"sender_name2,omitempty"`
	// 自社名3
	SenderName3 *string `json:"sender_name3,omitempty"`
	// 登録番号
	SenderRegistrationNumber *string `json:"sender_registration_number,omitempty"`
	// 自社TEL
	SenderTel *string `json:"sender_tel,omitempty"`
	// 自社郵便番号
	SenderZipCode *string `json:"sender_zip_code,omitempty"`
	// 消費税
	Tax *Number `json:"tax,omitempty"`
	// 消費税設定('INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税), 'NONENTRY': 税別表示(請求時に計算))
	TaxOption *string `json:"tax_option,omitempty"`
	// 消費税端数処理('CEIL': 切り上げ, 'FLOOR': 切り捨て, 'ROUND': 四捨五入)
	TaxRoundingPolicy *string `json:"tax_rounding_policy,omitempty"`
	// 小計
	TotalAmount *Number `json:"total_amount,omitempty"`
	// 合計
	TotalAmountIncludingTax *Number `json:"total_amount_including_tax,omitempty"`
}

// DeliverySlipDocumentItem は  を表す構造体です。
type DeliverySlipDocumentItem struct {
	// 品目
	Name *string `json:"name,omitempty"`
	// 金額
	Price *Number `json:"price,omitempty"`
	// 数量
	Quantity *Number `json:"quantity,omitempty"`
	// 消費税区分('STANDARD_TAX_10': 10%, 'REDUCED_TAX_8': 軽減8%, 'STANDARD_TAX_8': 8%, 'STANDARD_TAX_5': 5%, 'EXEMPTED_TAX': 対象外)
	TaxType *string `json:"tax_type,omitempty"`
	// 単位
	UnitName *string `json:"unit_name,omitempty"`
	// 単価
	UnitPrice *Number `json:"unit_price,omitempty"`
}

// Distribution は ApiEntity_Distribution model を表す構造体です。
type Distribution struct {
	// 作成日
	CreatedAt *string   `json:"created_at,omitempty"`
	Document  *Estimate `json:"document,omitempty"`
	// メール送信を識別する一意なID
	ID *int `json:"id,omitempty"`
	// メールのCC
	MailCc *string `json:"mail_cc,omitempty"`
	// 取引先へのメッセージ
	MailMessage *string `json:"mail_message,omitempty"`
	// 送信日時
	MailSentAt *string `json:"mail_sent_at,omitempty"`
	// メールの件名
	MailSubject *string `json:"mail_subject,omitempty"`
	// メールの宛先
	MailTo *string `json:"mail_to,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// Error は ApiEntity_Error model を表す構造体です。
type Error struct {
	// エラー理由
	Reasons []string `json:"reasons,omitempty"`
}

// Estimate は ApiEntity_Estimate model を表す構造体です。
type Estimate struct {
	// 処理済みに移動した日時
	ArchivedAt *string       `json:"archived_at,omitempty"`
	Body       *EstimateBody `json:"body,omitempty"`
	// 送り先を識別する一意なID。取引先を削除した場合もIDは残ります
	ContactID *int `json:"contact_id,omitempty"`
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// 見積書番号
	EstimateNumber *string `json:"estimate_number,omitempty"`
	// 発行ステータス
	EstimateStatus *int `json:"estimate_status,omitempty"`
	// 有効期限
	ExpireDate *string `json:"expire_date,omitempty"`
	// 見積書を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 発行日
	IssueDate *string `json:"issue_date,omitempty"`
	// 発行済かどうか（発行済の場合true）
	Issued *bool          `json:"issued,omitempty"`
	Items  []EstimateItem `json:"items,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// 受注ステータス
	PaymentStatus *int `json:"payment_status,omitempty"`
	// 取引先名
	RecipientName *string `json:"recipient_name,omitempty"`
	// 担当者
	RecipientNotes *string `json:"recipient_notes,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 件名
	Subject *string `json:"subject,omitempty"`
	// ごみ箱に移動した日時
	TrashedAt *string `json:"trashed_at,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ユーザID
	UserID *int `json:"user_id,omitempty"`
}

// EstimateBody は  を表す構造体です。
type EstimateBody struct {
	// 備考
	Notes *string `json:"notes,omitempty"`
	// 社内メモ
	PrivateSenderMemo *string `json:"private_sender_memo,omitempty"`
	// 取引先住所1
	RecipientAddress1 *string `json:"recipient_address1,omitempty"`
	// 取引先住所2
	RecipientAddress2 *string `json:"recipient_address2,omitempty"`
	// 取引先名1
	RecipientName1 *string `json:"recipient_name1,omitempty"`
	// 取引先名2
	RecipientName2 *string `json:"recipient_name2,omitempty"`
	// 取引先名3
	RecipientName3 *string `json:"recipient_name3,omitempty"`
	// 取引先名4
	RecipientName4 *string `json:"recipient_name4,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 取引先郵便番号
	RecipientZipCode *string `json:"recipient_zip_code,omitempty"`
	// 自社住所1
	SenderAddress1 *string `json:"sender_address1,omitempty"`
	// 自社住所2
	SenderAddress2 *string `json:"sender_address2,omitempty"`
	// 自社住所3
	SenderAddress3 *string `json:"sender_address3,omitempty"`
	// 自社Email
	SenderEmail *string `json:"sender_email,omitempty"`
	// 自社FAX
	SenderFax *string `json:"sender_fax,omitempty"`
	// 自社名1
	SenderName1 *string `json:"sender_name1,omitempty"`
	// 自社名2
	SenderName2 *string `json:"sender_name2,omitempty"`
	// 自社名3
	SenderName3 *string `json:"sender_name3,omitempty"`
	// 登録番号
	SenderRegistrationNumber *string `json:"sender_registration_number,omitempty"`
	// 自社TEL
	SenderTel *string `json:"sender_tel,omitempty"`
	// 自社郵便番号
	SenderZipCode *string `json:"sender_zip_code,omitempty"`
	// 消費税
	Tax *Number `json:"tax,omitempty"`
	// 消費税設定('INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税))
	TaxOption *string `json:"tax_option,omitempty"`
	// 消費税端数処理('CEIL': 切り上げ, 'FLOOR': 切り捨て, 'ROUND': 四捨五入)
	TaxRoundingPolicy *string `json:"tax_rounding_policy,omitempty"`
	// 小計
	TotalAmount *Number `json:"total_amount,omitempty"`
	// 合計
	TotalAmountIncludingTax *Number `json:"total_amount_including_tax,omitempty"`
}

// EstimateItem は  を表す構造体です。
type EstimateItem struct {
	// 品目
	Name *string `json:"name,omitempty"`
	// 金額
	Price *Number `json:"price,omitempty"`
	// 数量
	Quantity *Number `json:"quantity,omitempty"`
	// 消費税区分('STANDARD_TAX_10': 10%, 'REDUCED_TAX_8': 軽減8%, 'STANDARD_TAX_8': 8%, 'STANDARD_TAX_5': 5%, 'EXEMPTED_TAX': 対象外)
	TaxType *string `json:"tax_type,omitempty"`
	// 単位
	UnitName *string `json:"unit_name,omitempty"`
	// 単価
	UnitPrice *Number `json:"unit_price,omitempty"`
}

// Invoice は ApiEntity_Invoice model を表す構造体です。
type Invoice struct {
	// 処理済みに移動した日時
	ArchivedAt *string      `json:"archived_at,omitempty"`
	Body       *InvoiceBody `json:"body,omitempty"`
	// 送り先を識別する一意なID。取引先を削除した場合もIDは残ります
	ContactID *int `json:"contact_id,omitempty"`
	// 作成日
	CreatedAt *string `json:"created_at,omitempty"`
	// 請求書を識別する一意なID
	ID *int `json:"id,omitempty"`
	// 請求書番号
	InvoiceNumber *string `json:"invoice_number,omitempty"`
	// 入金履歴
	InvoicePaymentHistory *InvoicePaymentHistory `json:"invoice_payment_history,omitempty"`
	// 請求ステータス
	InvoiceStatus *int `json:"invoice_status,omitempty"`
	// 発行日
	IssueDate *string `json:"issue_date,omitempty"`
	// 発行済かどうか（発行済の場合true）
	Issued *bool         `json:"issued,omitempty"`
	Items  []InvoiceItem `json:"items,omitempty"`
	// 楽観ロックバージョン
	LockVersion *int `json:"lock_version,omitempty"`
	// お支払い期限
	PaymentDueOn *string `json:"payment_due_on,omitempty"`
	// 入金ステータス
	PaymentStatus *int `json:"payment_status,omitempty"`
	// 取引先名
	RecipientName *string `json:"recipient_name,omitempty"`
	// 担当者
	RecipientNotes *string `json:"recipient_notes,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 件名
	Subject *string `json:"subject,omitempty"`
	// ごみ箱に移動した日時
	TrashedAt *string `json:"trashed_at,omitempty"`
	// 更新日
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ユーザID
	UserID *int `json:"user_id,omitempty"`
}

// InvoicePostalMail は ApiEntity_InvoicePostalMail model を表す構造体です。
type InvoicePostalMail struct {
	// 発送状況
	DeliveryStatusResult *string  `json:"delivery_status_result,omitempty"`
	Invoice              *Invoice `json:"invoice,omitempty"`
}

// InvoiceBankAccount は  を表す構造体です。
type InvoiceBankAccount struct {
	// お振込先
	Detail *string `json:"detail,omitempty"`
}

// InvoiceBody は  を表す構造体です。
type InvoiceBody struct {
	// 源泉徴収税額
	AmountOfWithholdingTax *Number              `json:"amount_of_withholding_tax,omitempty"`
	BankAccounts           []InvoiceBankAccount `json:"bank_accounts,omitempty"`
	// 備考
	Notes *string `json:"notes,omitempty"`
	// 社内メモ
	PrivateSenderMemo *string `json:"private_sender_memo,omitempty"`
	// 取引先住所1
	RecipientAddress1 *string `json:"recipient_address1,omitempty"`
	// 取引先住所2
	RecipientAddress2 *string `json:"recipient_address2,omitempty"`
	// 取引先名1
	RecipientName1 *string `json:"recipient_name1,omitempty"`
	// 取引先名2
	RecipientName2 *string `json:"recipient_name2,omitempty"`
	// 取引先名3
	RecipientName3 *string `json:"recipient_name3,omitempty"`
	// 取引先名4
	RecipientName4 *string `json:"recipient_name4,omitempty"`
	// 取引先敬称
	RecipientTitle *string `json:"recipient_title,omitempty"`
	// 取引先郵便番号
	RecipientZipCode *string `json:"recipient_zip_code,omitempty"`
	// 自社住所1
	SenderAddress1 *string `json:"sender_address1,omitempty"`
	// 自社住所2
	SenderAddress2 *string `json:"sender_address2,omitempty"`
	// 自社住所3
	SenderAddress3 *string `json:"sender_address3,omitempty"`
	// 自社Email
	SenderEmail *string `json:"sender_email,omitempty"`
	// 自社FAX
	SenderFax *string `json:"sender_fax,omitempty"`
	// 自社名1
	SenderName1 *string `json:"sender_name1,omitempty"`
	// 自社名2
	SenderName2 *string `json:"sender_name2,omitempty"`
	// 自社名3
	SenderName3 *string `json:"sender_name3,omitempty"`
	// 登録番号
	SenderRegistrationNumber *string `json:"sender_registration_number,omitempty"`
	// 自社TEL
	SenderTel *string `json:"sender_tel,omitempty"`
	// 自社郵便番号
	SenderZipCode *string `json:"sender_zip_code,omitempty"`
	// 消費税
	Tax *Number `json:"tax,omitempty"`
	// 消費税設定('INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税))
	TaxOption *string `json:"tax_option,omitempty"`
	// 消費税端数処理('CEIL': 切り上げ, 'FLOOR': 切り捨て, 'ROUND': 四捨五入)
	TaxRoundingPolicy *string `json:"tax_rounding_policy,omitempty"`
	// 小計
	TotalAmount *Number `json:"total_amount,omitempty"`
	// 合計
	TotalAmountIncludingTax *Number `json:"total_amount_including_tax,omitempty"`
	// 源泉徴収税設定('None': なし, 'JapaneseStandard': あり(復興税なし), 'JapaneseStandardWithReconstructionTax': あり(復興税あり))
	WithholdingTaxType *string `json:"withholding_tax_type,omitempty"`
}

// InvoiceItem は  を表す構造体です。
type InvoiceItem struct {
	// 源泉徴収税フラグ
	ExcludingWithholdingTax *bool `json:"excluding_withholding_tax,omitempty"`
	// 品目
	Name *string `json:"name,omitempty"`
	// 金額
	Price *Number `json:"price,omitempty"`
	// 数量
	Quantity *Number `json:"quantity,omitempty"`
	// 消費税区分('STANDARD_TAX_10': 10%, 'REDUCED_TAX_8': 軽減8%, 'STANDARD_TAX_8': 8%, 'STANDARD_TAX_5': 5%, 'EXEMPTED_TAX': 対象外)
	TaxType *string `json:"tax_type,omitempty"`
	// 納品日
	TransactionDate *string `json:"transaction_date,omitempty"`
	// 単位
	UnitName *string `json:"unit_name,omitempty"`
	// 単価
	UnitPrice *Number `json:"unit_price,omitempty"`
}

// InvoicePaymentHistory は  を表す構造体です。
type InvoicePaymentHistory struct {
	// 最新の入金日
	LastPaidOn *string `json:"last_paid_on,omitempty"`
}

// User は ApiEntity_User model を表す構造体です。
type User struct {
	// 登録されているメールアドレス
	Email *string `json:"email,omitempty"`
	// ユーザーID
	ID *int `json:"id,omitempty"`
}

// CreateContactRequest は 送り先を作成します を表す構造体です。
type CreateContactRequest struct {
	// 取引先ID。取引先IDか取引先名どちらかを指定する必要があります。取引先IDを指定したときは、取引先名・敬称・ふりがな・消費税設定の指定が無視され、指定した取引先の値が使われます。
	ContactGroupID int `json:"contact_group_id,omitempty"`
	// メモ
	Memo string `json:"memo,omitempty"`
	// 住所1
	RecipientAddress1 string `json:"recipient_address1,omitempty"`
	// 住所2
	RecipientAddress2 string `json:"recipient_address2,omitempty"`
	// 管理コード
	RecipientCode string `json:"recipient_code,omitempty"`
	// FAX番号
	RecipientFaxNo string `json:"recipient_fax_no,omitempty"`
	// メールアドレス
	RecipientMailAddress string `json:"recipient_mail_address,omitempty"`
	// メールアドレス（CC）
	RecipientMailAddressCc string `json:"recipient_mail_address_cc,omitempty"`
	// 取引先名。取引先IDか取引先名どちらかを指定する必要があります。
	RecipientName string `json:"recipient_name,omitempty"`
	// 郵送先の宛名1
	RecipientName1 string `json:"recipient_name1,omitempty"`
	// 郵送先の宛名2
	RecipientName2 string `json:"recipient_name2,omitempty"`
	// 郵送先の宛名3
	RecipientName3 string `json:"recipient_name3,omitempty"`
	// 郵送先の宛名4
	RecipientName4 string `json:"recipient_name4,omitempty"`
	// 部署・担当者
	RecipientNotes string `json:"recipient_notes,omitempty"`
	// ふりがな
	RecipientRuby string `json:"recipient_ruby,omitempty"`
	// 電話番号
	RecipientTelNo string `json:"recipient_tel_no,omitempty"`
	// 敬称
	RecipientTitle string `json:"recipient_title,omitempty"`
	// 郵送先の敬称
	RecipientTitle2 string `json:"recipient_title2,omitempty"`
	// 郵便番号
	RecipientZipCode string `json:"recipient_zip_code,omitempty"`
	// 消費税設定('USE_SENDER': 自社情報の設定, 'INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税), 'NONENTRY': 税別表示(納品書のみ請求時に計算))
	TaxOption string `json:"tax_option,omitempty"`
}

// CreateContactGroupRequest は 取引先を作成します を表す構造体です。
type CreateContactGroupRequest struct {
	BankAccounts []interface{} `json:"bank_accounts,omitempty"`
	MailSettings interface{}   `json:"mail_settings,omitempty"`
	// Peppol ID
	PeppolID string `json:"peppol_id,omitempty"`
	// 取引先名
	RecipientName string `json:"recipient_name,omitempty"`
	// ふりがな
	RecipientRuby string `json:"recipient_ruby,omitempty"`
	// 敬称
	RecipientTitle string `json:"recipient_title,omitempty"`
	// 消費税設定('USE_SENDER': 自社情報の設定, 'INCLUDE': 税込表示, 'EXCLUDE': 税別表示, 'EXEMPT': 税込表示(免税), 'NONENTRY': 税別表示(納品書のみ請求時に計算))
	TaxOption string `json:"tax_option,omitempty"`
}

// CreateDealingItemRequest は 品目を作成します を表す構造体です。
type CreateDealingItemRequest struct {
	// 源泉徴収税フラグ
	ExcludingWithholdingTax bool `json:"excluding_withholding_tax,omitempty"`
	// 品番・品名
	Name string `json:"name,omitempty"`
	// 消費税区分('USE_SENDER': 自社情報の設定, 'STANDARD_TAX_10': 10%, 'REDUCED_TAX_8': 軽減8%, 'STANDARD_TAX_8': 8%, 'STANDARD_TAX_5': 5%, 'EXEMPTED_TAX': 対象外)
	TaxType string `json:"tax_type,omitempty"`
	// 単位
	UnitName string `json:"unit_name,omitempty"`
	// 単価
	UnitPrice Number `json:"unit_price,omitempty"`
}

// CreateDeliverySlipRequest は 納品書を作成します を表す構造体です。
type CreateDeliverySlipRequest struct {
	Body interface{} `json:"body,omitempty"`
	// 送り先ID
	ContactID int `json:"contact_id,omitempty"`
	// 納品日
	DeliveryDate string `json:"delivery_date,omitempty"`
	// 納品書番号
	DeliverySlipNumber string `json:"delivery_slip_number,omitempty"`
	// 発行日
	IssueDate string        `json:"issue_date,omitempty"`
	Items     []interface{} `json:"items,omitempty"`
	// 件名
	Subject string `json:"subject,omitempty"`
}

// CreateEstimateRequest は 見積書を作成します を表す構造体です。
type CreateEstimateRequest struct {
	Body interface{} `json:"body,omitempty"`
	// 送り先ID
	ContactID int `json:"contact_id,omitempty"`
	// 見積書番号
	EstimateNumber string `json:"estimate_number,omitempty"`
	// 有効期限
	ExpireDate string `json:"expire_date,omitempty"`
	// 発行日
	IssueDate string        `json:"issue_date,omitempty"`
	Items     []interface{} `json:"items,omitempty"`
	// 件名
	Subject string `json:"subject,omitempty"`
}

// DistributeEstimateRequest は 見積書をメール送信します を表す構造体です。
type DistributeEstimateRequest struct {
	// 自分自身にccを送るかどうか
	IncludingSelfToCc bool `json:"including_self_to_cc,omitempty"`
	// 本文
	MailBody string `json:"mail_body,omitempty"`
	// 取引先へのメッセージ、本文を指定する場合は無視されます
	MailMessage string `json:"mail_message,omitempty"`
	// 件名
	MailSubject string `json:"mail_subject,omitempty"`
}

// CreateInvoiceRequest は 請求書を作成します を表す構造体です。
type CreateInvoiceRequest struct {
	Body interface{} `json:"body,omitempty"`
	// 送り先ID
	ContactID int `json:"contact_id,omitempty"`
	// 請求書番号
	InvoiceNumber string `json:"invoice_number,omitempty"`
	// 請求日
	IssueDate string        `json:"issue_date,omitempty"`
	Items     []interface{} `json:"items,omitempty"`
	// お支払い期限
	PaymentDueOn string `json:"payment_due_on,omitempty"`
	// 件名
	Subject string `json:"subject,omitempty"`
}

// MarkInvoicePaidRequest は 請求書を入金済にします を表す構造体です。
type MarkInvoicePaidRequest struct {
	// 入金日。指定しない場合、かつ、請求書のお支払い期限が設定済みの場合、お支払い期限を入金日にします。
	PaidOn string `json:"paid_on,omitempty"`
}
